
<MyBox>:
	orientation: 'vertical'
	Label:
		text: 'Cedula'
		font_size: 50

	TextInput:
		multiline: False
		font_size: 50
		id: cedula_input

	Label:
		text: 'Placa'
		font_size: 50

	TextInput:
		multiline: False
		font_size: 50
		id: placa_input

	Button: 
		text: 'Registrar'
		font_size: 50
		on_press: app.registerHandler(cedula_input.text, placa_input.text)
	
	Label:
		text: ''
		font_size: 20
		id: registrar_label
	
